version: '3'

services:
  mysql_ansi_db:
    container_name: mysql_ansi_db
    env_file: compose.env
    build:
      context: ./
      dockerfile: dockerfile
      args:
        DB_PASSWORD: ${PASSWORD}
    restart: always
    ports:
      - 3306:3306

  mysql_ansi_dbms:
    container_name: mysql_ansi_dbms
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_ansi_db