namespace Database.Models;

public static class IngredientsTagsTypes
{
public static readonly string Beef ="Wołowina";
public static readonly string Turkey ="Indyk";
public static readonly string CrabMeat ="Mięso Kraba";
public static readonly string Chicken ="Kurczak";
public static readonly string Pork ="Wieprzowina";
public static readonly string Shrimp ="Krewetki";
public static readonly string Lentils ="Soczewica";
public static readonly string Corn ="Kukurydza";
public static readonly string Lamb ="Jagnięcina";
public static readonly string Eggplant ="Bakłażan";
public static readonly string Tomato ="Pomidor";
public static readonly string Cod ="Dorsz";
public static readonly string Perch ="Okoń";
public static readonly string Chickpea ="Ciecierzyca";
public static readonly string Pumpkin ="Dynia";
public static readonly string Duck ="Kaczka";
public static readonly string Pasta ="Makaron";
public static readonly string Egg ="Jajko";
public static readonly string Mutton ="Baranina";
public static readonly string Asparagus ="Szparagi";
public static readonly string Cheese ="Ser";
public static readonly string Salmon ="Łosoś";
public static readonly string PikePerch ="Sandacz";
public static readonly string RedBean ="Czerwona Fasola";
public static readonly string Gnocchi ="Gnocchi";
public static readonly string Cabbage ="Kapusta";
public static readonly string SweetPotatoes ="Bataty";
public static readonly string Spinach ="Szpinak";
public static readonly string Cucumbers ="Ogórki";
public static readonly string StringBean ="Fasola Szparagowa";
public static readonly string Calamari ="Kalmary";
public static readonly string Garlic ="Czosnek";
public static readonly string Apples ="Jabłka";
public static readonly string Pepper ="Papryka";
public static readonly string Pea ="Groch";
public static readonly string Tofu ="Tofu";
public static readonly string Zucchini ="Cukinia";
public static readonly string Acorns ="Żołędzie";
public static readonly string Potatoes ="Ziemniaki";
public static readonly string Leek ="Por";
public static readonly string Tuna ="Tuńczyk";
public static readonly string Carrot ="Marchew";
public static readonly string Veal ="Cielęcina";
public static readonly string Herring ="Śledź";
public static readonly string Mushrooms ="Grzyby";
public static readonly string Cauliflower ="Kalafior";
public static readonly string Trout ="Pstrąg";
public static readonly string Mackerel ="Makrela";
public static readonly string Kohlrabi ="Kalarepa";
public static readonly string Olives ="Oliwki";
public static readonly string Groats ="Kasza";
public static readonly string Soy ="Soja";
}