CREATE DATABASE ANSI;
USE ANSI;

CREATE TABLE DISH_TYPE
(
    DISH_TYPE_ID INT NOT NULL AUTO_INCREMENT,
    DISH_DIFFICULTY VARCHAR(100) NOT NULL,
    MAIN_CATEGORY VARCHAR(100) NOT NULL,
    PRIMARY KEY (DISH_TYPE_ID)
);

CREATE TABLE DOMINANT_INDEGRIENT
(
    DOMINANT_INDEGRIENT_ID INT NOT NULL AUTO_INCREMENT,
    INDEGRIENT_NAME VARCHAR(100),
    PRIMARY KEY (DOMINANT_INDEGRIENT_ID)
);

CREATE TABLE DISH
(
    DISH_ID INT NOT NULL AUTO_INCREMENT,
    DISH_TYPE_ID INT NOT NULL,
    MAKE_TIME_MIN INT NOT NULL,
    DISH_RECIPE_URL VARCHAR(300),
    PRIMARY KEY (DISH_ID),
    FOREIGN KEY (DISH_TYPE_ID) REFERENCES DISH_TYPE(DISH_TYPE_ID)
);

CREATE TABLE DISH_DOMINANT_INDEGRIENT
(
    DOMINANT_INDEGRIENT_ID INT NOT NULL,
    DISH_ID INT NOT NULL,
    FOREIGN KEY (DOMINANT_INDEGRIENT_ID) REFERENCES DOMINANT_INDEGRIENT(DOMINANT_INDEGRIENT_ID),
    FOREIGN KEY (DISH_ID) REFERENCES DISH(DISH_ID)
);

