CREATE DATABASE ANSI;
USE ANSI;

CREATE TABLE DISH
(
    DISH_ID INT NOT NULL AUTO_INCREMENT,
    DISH_NAME VARCHAR(150) NOT NULL,
    MAIN_CATEGORY VARCHAR(100) NOT NULL,
    MAKE_TIME_MIN INT NOT NULL,
    PREPARATION_DIFFICULTY VARCHAR(50) NOT NULL,
    INGREDIENTS_CATEGORY VARCHAR(50) NOT NULL,
    INGREDIENTS_TAGS VARCHAR(300) NOT NULL,
    DISH_RECIPE_URL VARCHAR(300),
    PRIMARY KEY (DISH_ID)
);

SET NAMES utf8mb4;
# sql input queries
INSERT INTO `DISH` (`DISH_ID`, `DISH_NAME`, `MAIN_CATEGORY`, `MAKE_TIME_MIN`, `PREPARATION_DIFFICULTY`, `INGREDIENTS_CATEGORY`, `INGREDIENTS_TAGS`, `DISH_RECIPE_URL`) VALUES
(332,	'Antrykot wołowy po amerykańsku',	'Amerykańska',	45,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/antrykot-wolowy-po-amerykansku'),
(333,	'Hamburgery z indyka',	'Amerykańska',	45,	'średni',	'Mięso',	'Indyk',	'https://www.przepisy.pl/przepis/hamburgery-z-indyka'),
(334,	'Placki krabowe w stylu nowoorleańskim',	'Amerykańska',	40,	'łatwy',	'Ryby',	'Mięso Kraba',	'https://www.przepisy.pl/przepis/placki-krabowe-w-stylu-nowoorleanskim'),
(335,	'Pikantne skrzydełka Buffalo',	'Amerykańska',	45,	'łatwy',	'Wege',	'Kurczak',	'https://www.przepisy.pl/przepis/pikantne-skrzydelka-buffalo'),
(336,	'Żeberka BBQ',	'Amerykańska',	90,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/zeberka-bbq'),
(337,	'Cheeseburger z kolendrą (na ostro)',	'Amerykańska',	45,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/cheeseburger-z-kolendra'),
(338,	'Zupa gumbo z krewetkami i okrą',	'Amerykańska',	35,	'łatwy',	'Ryby',	'Krewetki',	'https://www.przepisy.pl/przepis/zupa-gumbo-z-krewetkami-i-okra'),
(339,	'Burger z czerwonej i czarnej soczewicy',	'Amerykańska',	45,	'łatwy',	'Wege',	'Soczewica',	'https://www.przepisy.pl/przepis/burger-z-czerwonej-i-czarnej-soczewicy'),
(340,	'Zupa z kukurydzy z czosnkiem',	'Amerykańska',	30,	'łatwy',	'Wege',	'Kukurydza',	'https://www.przepisy.pl/przepis/zupa-z-kukurydzy-z-czosnkiem'),
(341,	'Bułgarski gulasz Gjuwecz',	'Bałkańska',	90,	'łatwy',	'Mięso',	'Jagnięcina',	'https://www.przepisy.pl/przepis/bulgarski-gulasz-gjuwecz'),
(342,	'Cevapcici winne z sałatką',	'Bałkańska',	90,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/cevapcici-winne-z-salatka'),
(343,	'Klopsy po bałkańsku',	'Bałkańska',	45,	'łatwy',	'Mięso',	'Jagnięcina',	'https://www.przepisy.pl/przepis/klopsy-po-balkansku'),
(344,	'Szaszłyki wołowe z papryką i rozmarynem',	'Bałkańska',	30,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/szaszlyki-wolowe-z-papryka-i-rozmarynem'),
(345,	'Kociołek z wołowiną',	'Bałkańska',	45,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/kociolek-z-wolowina'),
(346,	'Zapiekanka z bakłażanem i fetą',	'Bałkańska',	45,	'łatwy',	'Wege',	'Bakłażan',	'https://www.przepisy.pl/przepis/zapiekanka-z-baklazanem-i-feta'),
(347,	'Sałatka bułgarska',	'Bałkańska',	30,	'łatwy',	'Wege',	'Pomidor',	'https://www.przepisy.pl/przepis/salatka-bulgarska-2'),
(348,	'Izraelskie klopsiki zapiekane z pastą tahini i Za’atarem',	'Bliskiego Wschodu',	30,	'łatwy',	'Mięso',	'Indyk',	'https://www.przepisy.pl/przepis/izraelskie-klopsiki-zapiekane-z-pasta-tahini-i-zaatarem'),
(349,	'Placki rybne z ciecierzycą',	'Bliskiego Wschodu',	40,	'łatwy',	'Ryby',	'Dorsz',	'https://www.przepisy.pl/przepis/placki-rybne-z-ciecierzyca'),
(350,	'Kurczak po libańsku',	'Bliskiego Wschodu',	25,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-po-libansku-2'),
(351,	'Adana kebab',	'Bliskiego Wschodu',	40,	'łatwy',	'Mięso',	'Jagnięcina',	'https://www.przepisy.pl/przepis/adana-kebab'),
(352,	'Pieczony okoń morski z Za’atarem',	'Bliskiego Wschodu',	40,	'łatwy',	'Ryby',	'Okoń',	'https://www.przepisy.pl/przepis/pieczony-okon-morski-z-zaatarem'),
(353,	'Sznycel po izraelsku',	'Bliskiego Wschodu',	40,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/sznycel-po-izraelsku'),
(354,	'Pieczony kurczak z kawałkami granatu',	'Bliskiego Wschodu',	70,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/pieczony-kurczak-z-kawalkami-granatu'),
(355,	'Chrupiąca ciecierzyca z przyprawą Za’atar',	'Bliskiego Wschodu',	40,	'łatwy',	'Wege',	'Ciecierzyca',	'https://www.przepisy.pl/przepis/chrupiaca-ciecierzyca-z-przyprawa-zaatar'),
(356,	'Frytki z pieczonego bakłażana z dipem tahini',	'Bliskiego Wschodu',	40,	'łatwy',	'Wege',	'Bakłażan',	'https://www.przepisy.pl/przepis/frytki-z-pieczonego-baklazana-z-dipem-tahini'),
(357,	'Sałatka z pieczonej dyni',	'Bliskiego Wschodu',	40,	'łatwy',	'Wege',	'Dynia',	'https://www.przepisy.pl/przepis/salatka-z-pieczonej-dyni'),
(358,	'Pomidorowa sałatka z grzankami z chlebka pita doprawiona za’atarem',	'Bliskiego Wschodu',	40,	'łatwy',	'Wege',	'Pomidor',	'https://www.przepisy.pl/przepis/pomidorowa-salatka-z-grzankami-z-chlebka-pita-doprawiona-zaatarem'),
(359,	'Domowy humus',	'Bliskiego Wschodu',	35,	'łatwy',	'Wege',	'Ciecierzyca',	'https://www.przepisy.pl/przepis/domowy-humus'),
(360,	'Wołowina z imbirem i warzywami',	'Chińska',	60,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/wolowina-z-imbirem-i-warzywami'),
(361,	'Amok Moan - Kurczak po kambodżańsku',	'Chińska',	30,	'średni',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/amok-moan-kurczak-po-kambodzansku'),
(362,	'Kurczak w curry z makaronem',	'Chińska',	35,	'średni',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-w-curry-z-makaronem'),
(363,	'Kurczak po seczuańsku',	'Chińska',	45,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-po-seczuansku-2'),
(364,	'Wołowina Ame Hnat',	'Chińska',	45,	'średni',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/wolowina-ame-hnat'),
(365,	'Kaczka po pekińsku',	'Chińska',	90,	'trudny',	'Mięso',	'Kaczka',	'https://www.przepisy.pl/przepis/kaczka-po-pekinsku'),
(366,	'Smażony makaron z tofu i warzywami',	'Chińska',	25,	'łatwy',	'Wege',	'Makaron',	'https://www.przepisy.pl/przepis/smazony-makaron-z-tofu-i-warzywami'),
(367,	'Zupa z jajkiem',	'Chińska',	30,	'łatwy',	'Wege',	'Jajko',	'https://www.przepisy.pl/przepis/zupa-z-jajkiem'),
(368,	'Boeuf Bourguignon',	'Francuska',	90,	'średni',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/boeuf-bourguignon'),
(369,	'Antrykot z kurczaka po francusku',	'Francuska',	30,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/antrykot-z-kurczaka-po-francusku'),
(370,	'Polędwiczki duszone z cebulą i musztardą',	'Francuska',	45,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/poledwiczki-duszone-z-cebula-i-musztarda-video'),
(371,	'Roladki z piersi indyka',	'Francuska',	60,	'łatwy',	'Mięso',	'Indyk',	'https://www.przepisy.pl/przepis/roladki-z-piersi-indyka'),
(372,	'Francuski gulasz z winem',	'Francuska',	45,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/francuski-gulasz-z-winem'),
(373,	'Kaczka z winogronami',	'Francuska',	90,	'trudny',	'Mięso',	'Kaczka',	'https://www.przepisy.pl/przepis/kaczka-z-winogronami'),
(374,	'Boeuf a’la mode – klasyczna pieczeń wołowa',	'Francuska',	90,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/boeuf-ala-mode-klasyczna-pieczen-wolowa'),
(375,	'Baranina z czerwonym winem i rozmarynem',	'Francuska',	90,	'łatwy',	'Mięso',	'Baranina',	'https://www.przepisy.pl/przepis/baranina-z-czerwonym-winem-i-rozmarynem'),
(376,	'Kurczak de volaille z suszoną morelą',	'Francuska',	45,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-de-volaille-z-suszona-morela'),
(377,	'Tarta z porem i szparagami',	'Francuska',	60,	'łatwy',	'Wege',	'Szparagi',	'https://www.przepisy.pl/przepis/tarta-z-porem-i-szparagami'),
(378,	'Zupa z zielonych szparagów',	'Francuska',	45,	'łatwy',	'Wege',	'Szparagi',	'https://www.przepisy.pl/przepis/zupa-z-zielonych-szparagow'),
(379,	'Ser panierowany z sosem jagodowym',	'Francuska',	30,	'łatwy',	'Wege',	'Ser',	'https://www.przepisy.pl/przepis/ser-panierowany-z-sosem-jagodowym'),
(380,	'Piersi z kaczki wędzone w herbacie earl grey',	'Fusion',	45,	'łatwy',	'Mięso',	'Kaczka',	'https://www.przepisy.pl/przepis/piersi-z-kaczki-wedzone-w-herbacie-earl-grey'),
(381,	'Pieczony łosoś z sosem pomarańczowym',	'Fusion',	30,	'łatwy',	'Ryby',	'Łosoś',	'https://www.przepisy.pl/przepis/pieczony-losos-z-sosem-pomaranczowym'),
(382,	'Kotleciki panierowane w płatkach owsianych',	'Fusion',	30,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kotleciki-panierowane-w-platkach-owsianych'),
(383,	'Łosoś z pistacjową panierką na puree z kalafiora',	'Fusion',	45,	'łatwy',	'Ryby',	'Łosoś',	'https://www.przepisy.pl/przepis/losos-z-pistacjowa-panierka-na-puree-z-kalafiora'),
(384,	'Koreczki z indyka ze śliwką',	'Fusion',	30,	'łatwy',	'Mięso',	'Indyk',	'https://www.przepisy.pl/przepis/koreczki-z-indyka-ze-sliwka'),
(385,	'Ravioli z konfitowaną kaczką',	'Fusion',	250,	'trudny',	'Mięso',	'Kaczka',	'https://www.przepisy.pl/przepis/ravioli-z-konfitowana-kaczka'),
(386,	'Sałatka z chrupiących warzyw z wołowiną z chilli',	'Fusion',	30,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/salatka-z-chrupiacych-warzyw-z-wolowina-z-chilli'),
(387,	'Sandacz glazurowany sosem imbirowym',	'Fusion',	30,	'łatwy',	'Ryby',	'Sandacz',	'https://www.przepisy.pl/przepis/sandacz-glazurowany-sosem-imbirowym'),
(388,	'Wrapy z tortilli z czerwoną fasolą i warzywami',	'Fusion',	40,	'łatwy',	'Wege',	'Czerwona Fasola',	'https://www.przepisy.pl/przepis/wrapy-z-tortilli-z-czerwona-fasola-i-warzywami'),
(389,	'Gnocchi z skorzonerą, pietruszką i masłem',	'Fusion',	20,	'łatwy',	'Wege',	'Gnocchi',	'https://www.przepisy.pl/przepis/gnocchi-z-skorzonera-pietruszka-i-maslem'),
(390,	'Curry z Pak choi',	'Fusion',	30,	'łatwy',	'Wege',	'Kapusta',	'https://www.przepisy.pl/przepis/curry-z-pak-choi'),
(391,	'Placki z batatów',	'Fusion',	30,	'łatwy',	'Wege',	'Bataty',	'https://www.przepisy.pl/przepis/placki-z-batatow-video'),
(392,	'Quiche z pak choi',	'Fusion',	95,	'łatwy',	'Wege',	'Kapusta',	'https://www.przepisy.pl/przepis/quiche-z-pak-choi'),
(393,	'Krewetki z sosem pomidorowym i fetą',	'Grecka',	30,	'łatwy',	'Ryby',	'Krewetki',	'https://www.przepisy.pl/przepis/krewetki-z-sosem-pomidorowym-i-feta'),
(394,	'Grillowana pierś z kurczaka z dynią, serem feta i świeżą kolendrą',	'Grecka',	45,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/grillowana-piers-z-kurczaka-z-dynia-serem-feta-i-swieza-kolendra'),
(395,	'Moussaka',	'Grecka',	90,	'łatwy',	'Mięso',	'Baranina',	'https://www.przepisy.pl/przepis/moussaka'),
(396,	'Gulasz jagnięcy z cukinią',	'Grecka',	60,	'średni',	'Mięso',	'Jagnięcina',	'https://www.przepisy.pl/przepis/gulasz-jagniecy-z-cukinia'),
(397,	'Gyros',	'Grecka',	30,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/gyros'),
(398,	'Kofty z sosem jogurtowym',	'Grecka',	30,	'łatwy',	'Mięso',	'Baranina',	'https://www.przepisy.pl/przepis/kofty-z-sosem-jogurtowym'),
(399,	'Kotlety schabowe z pigwą',	'Grecka',	60,	'średni',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/kotlety-schabowe-z-pigwa'),
(400,	'Pulpety z miętą i cytryną po grecku',	'Grecka',	45,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/pulpety-z-mieta-i-cytryna-po-grecku'),
(401,	'Wegetariańskie pikantne kotlety z zielonej soczewicy',	'Grecka',	30,	'łatwy',	'Wege',	'Soczewica',	'https://www.przepisy.pl/przepis/wegetarianskie-pikantne-kotlety-z-zielonej-soczewicy'),
(402,	'Spanakopita, czyli grecka tarta',	'Grecka',	50,	'łatwy',	'Wege',	'Szpinak',	'https://www.przepisy.pl/przepis/spanakopita-czyli-grecka-tarta'),
(403,	'Chłodnik ogórkowy',	'Grecka',	15,	'średni',	'Wege',	'Ogórki',	'https://www.przepisy.pl/przepis/chlodnik-ogorkowy-1'),
(404,	'Marynowany bakłażan',	'Grecka',	30,	'łatwy',	'Wege',	'Bakłażan',	'https://www.przepisy.pl/przepis/marynowany-baklazan'),
(405,	'Tiropitakia czyli greckie pierożki z serem',	'Grecka',	60,	'średni',	'Wege',	'Ser',	'https://www.przepisy.pl/przepis/tiropitakia-czyli-greckie-pierozki-z-serem'),
(406,	'Gruzińskie szaszłyki z jagnięciny z sosem Tkemali',	'Gruzińska',	90,	'średni',	'Mięso',	'Jagnięcina',	'https://www.przepisy.pl/przepis/gruzinskie-szaszlyki-z-jagnieciny-z-sosem-tkemali'),
(407,	'Kurczak czkmeruli',	'Gruzińska',	60,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-czkmeruli'),
(408,	'Charczo',	'Gruzińska',	110,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/charczo'),
(409,	'Gulasz z haluszkami ze szpinakiem',	'Gruzińska',	110,	'średni',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/gulasz-z-haluszkami-ze-szpinakiem'),
(410,	'Odżachuri',	'Gruzińska',	60,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.polakogruzin.pl/przepis-odzachuri-klasyczna-gruzinska-jednogarnkowka/'),
(411,	'Lobiani – gruziński placek z fasolą',	'Gruzińska',	80,	'łatwy',	'Wege',	'Czerwona Fasola',	'https://www.przepisy.pl/przepis/lobiani-gruzinski-placek-z-fasola'),
(412,	'Gruzińska sałatka z fasolką szparagowa',	'Gruzińska',	15,	'łatwy',	'Wege',	'Fasola Szparagowa',	'https://www.przepisy.pl/przepis/gruzinska-salatka-z-fasolka-szparagowa'),
(413,	'Nigviziani badrigiani',	'Gruzińska',	30,	'łatwy',	'Wege',	'Bakłażan',	'https://www.przepisy.pl/przepis/nigviziani-badrigiani'),
(414,	'Chaczapuri - zapiekanka gruzińska',	'Gruzińska',	60,	'średni',	'Wege',	'Ser',	'https://www.przepisy.pl/przepis/chaczapuri-zapiekanka-gruzinska'),
(415,	'Szaszłyki z indyka z chorizo',	'Hiszpańska',	30,	'łatwy',	'Mięso',	'Indyk',	'https://www.przepisy.pl/przepis/szaszlyki-z-indyka-z-chorizo'),
(416,	'Empanadas',	'Hiszpańska',	60,	'średni',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/empanadas'),
(417,	'Fabada Asturiana',	'Hiszpańska',	120,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/fabada-asturiana-2'),
(418,	'Kalmary nadziewane',	'Hiszpańska',	60,	'średni',	'Ryby',	'Kalmary',	'https://www.przepisy.pl/przepis/kalmary-nadziewane'),
(419,	'Dorsz po hiszpańsku',	'Hiszpańska',	45,	'średni',	'Ryby',	'Dorsz',	'https://www.przepisy.pl/przepis/dorsz-po-hiszpansku'),
(420,	'Krewetki z pietruszką',	'Hiszpańska',	15,	'łatwy',	'Ryby',	'Krewetki',	'https://www.przepisy.pl/przepis/krewetki-z-pietruszka'),
(421,	'Tortilla z chorizo',	'Hiszpańska',	45,	'średni',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/tortilla-z-chorizo'),
(422,	'Hiszpańska zupa czosnkowa z grzankami',	'Hiszpańska',	30,	'łatwy',	'Wege',	'Czosnek',	'https://www.przepisy.pl/przepis/hiszpanska-zupa-czosnkowa-z-czosnkowymi-grzankami'),
(423,	'Hiszpański placek z jabłkami',	'Hiszpańska',	60,	'łatwy',	'Wege',	'Jabłka',	'https://www.przepisy.pl/przepis/hiszpanski-placek-z-jablkami-2'),
(424,	'Papryka nadziewana z oliwkami',	'Hiszpańska',	45,	'łatwy',	'Wege',	'Papryka',	'https://www.przepisy.pl/przepis/papryka-nadziewana-z-oliwkami'),
(425,	'Kurczak w sosie curry z pomidorami',	'Indyjska',	45,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-w-sosie-curry-z-pomidorami'),
(426,	'Kurczak w czerwonym curry',	'Indyjska',	30,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-w-czerwonym-curry'),
(427,	'Baranina madras',	'Indyjska',	60,	'łatwy',	'Mięso',	'Baranina',	'https://www.przepisy.pl/przepis/baranina-madras'),
(428,	'Seekh kebab',	'Indyjska',	30,	'łatwy',	'Mięso',	'Baranina',	'https://www.przepisy.pl/przepis/seekh-kebab'),
(429,	'Orientalna wołowina z orzechami i sezamem',	'Indyjska',	30,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/orientalna-wolowina-z-orzechami-i-sezamem'),
(430,	'Kurczak tandoori',	'Indyjska',	90,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-tandoori-2'),
(431,	'Chana dal – potrawka z grochu',	'Indyjska',	20,	'łatwy',	'Wege',	'Groch',	'https://www.przepisy.pl/przepis/chana-dal-potrawka-z-grochu'),
(432,	'Tofu w kremowym sosie tikka masala',	'Indyjska',	30,	'łatwy',	'Wege',	'Tofu',	'https://www.przepisy.pl/przepis/tofu-w-kremowym-sosie-tikka-masala'),
(433,	'Chłodnik z cukinii',	'Indyjska',	30,	'łatwy',	'Wege',	'Cukinia',	'https://www.przepisy.pl/przepis/chlodnik-z-cukinii'),
(434,	'Smażone skrzydełka po koreańsku',	'Koreańska',	15,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/smazone-skrzydelka-po-koreansku'),
(435,	'Grillowane kalmary',	'Koreańska',	15,	'łatwy',	'Ryby',	'Kalmary',	'https://www.przepisy.pl/przepis/grillowane-kalmary'),
(436,	'Dakgangjeong, czyli chrupiący kurczak po koreańsku',	'Koreańska',	15,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/dakgangjeong-czyli-chrupiacy-kurczak-po-koreansku'),
(437,	'Koreańskie Bulgogi',	'Koreańska',	20,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/koreanskie-bulgogi'),
(438,	'Japche – makaron ryżowy z kurczakiem w grillowej marynacie',	'Koreańska',	20,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/japche-makaron-ryzowy-z-kurczakiem-w-grillowej-marynacie'),
(439,	'Tangsuyuk – słodko-kwaśna wieprzowina po koreańsku',	'Koreańska',	30,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/tangsuyuk-slodko-kwasna-wieprzowina-po-koreansku'),
(440,	'Pieczona łopatka wieprzowa Gochujang',	'Koreańska',	25,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/pieczona-lopatka-wieprzowa-gochujang'),
(441,	'Koreański burger',	'Koreańska',	15,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/koreanski-burger'),
(442,	'Kimchi',	'Koreańska',	1440,	'łatwy',	'Wege',	'Kapusta',	'https://kukbuk.pl/artykuly/jak-zrobic-prawdziwe-kimchi/'),
(443,	'Dotori muk',	'Koreańska',	1500,	'łatwy',	'Wege',	'Żołędzie',	'https://dziendobry.tvn.pl/przepisy-kulinarne/slona-galaretka-z-zoledzi-prosty-przepis-na-dotori-muk-5441567'),
(444,	'Burritos',	'Meksykańska',	30,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/burritos-2'),
(445,	'Meksykański kurczak pod pierzynką',	'Meksykańska',	45,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/meksykanski-kurczak-pod-pierzynka'),
(446,	'Grillowane steki z rostbefu z Tequilą',	'Meksykańska',	30,	'średni',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/grillowane-steki-z-rostbefu-z-tequila'),
(447,	'Schab po meksykańsku',	'Meksykańska',	30,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/schab-po-meksykansku'),
(448,	'Meksykańska potrawka z kurczakiem',	'Meksykańska',	25,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/meksykanska-potrawka-z-kurczakiem'),
(449,	'Chili Con Carne',	'Meksykańska',	45,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/chili-con-carne'),
(450,	'Wrapy z tortilli z czerwoną fasolą i warzywami',	'Meksykańska',	40,	'łatwy',	'Wege',	'Czerwona Fasola',	'https://www.przepisy.pl/przepis/wrapy-z-tortilli-z-czerwona-fasola-i-warzywami'),
(451,	'Rumiane kotlety schabowe z sosem piwnym',	'Niemiecka',	30,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/rumiane-kotlety-schabowe-z-sosem-piwnym'),
(452,	'Golonka po bawarsku',	'Niemiecka',	90,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/golonka-po-bawarsku'),
(453,	'Pichelsteiner czyli gulasz po niemiecku',	'Niemiecka',	90,	'średni',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/pichelsteiner-czyli-gulasz-po-niemiecku'),
(454,	'Knedle ziołowe',	'Niemiecka',	60,	'trudny',	'Wege',	'Ziemniaki',	'https://www.przepisy.pl/przepis/knedle-ziolowe'),
(455,	'Reibekuchen, czyli chrupiące niemieckie placki ziemniaczane',	'Niemiecka',	30,	'łatwy',	'Wege',	'Ziemniaki',	'https://www.przepisy.pl/przepis/reibekuchen-czyli-chrupiace-niemieckie-placki-ziemniaczane'),
(456,	'Sałatka z porów',	'Niemiecka',	20,	'łatwy',	'Wege',	'Por',	'https://www.przepisy.pl/przepis/salatka-z-porow'),
(457,	'Kaczka w sosie cytrynowym',	'Orientalna',	90,	'łatwy',	'Mięso',	'Kaczka',	'https://www.przepisy.pl/przepis/kaczka-w-sosie-cytrynowym'),
(458,	'Wieprzowa polędwiczka w orzechowym sosie',	'Orientalna',	30,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/wieprzowa-poledwiczka-w-orzechowym-sosie'),
(459,	'Kurczak duszony w napoju kokosowym',	'Orientalna',	30,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-duszony-w-napoju-kokosowym'),
(460,	'Zupa Pho Bo z Wietnamu',	'Orientalna',	450,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/zupa-pho-bo-z-wietnamu'),
(461,	'Duszona wołowina po wietnamsku – Bò Kho',	'Orientalna',	90,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/duszona-wolowina-po-wietnamsku-bo-kho'),
(462,	'Tuńczyk w orientalnym sosie',	'Orientalna',	30,	'łatwy',	'Ryby',	'Tuńczyk',	'https://www.przepisy.pl/przepis/tunczyk-w-orientalnym-sosie-video'),
(463,	'Smażone krewetki w delikatnym curry',	'Orientalna',	30,	'łatwy',	'Ryby',	'Krewetki',	'https://www.przepisy.pl/przepis/smazone-krewetki-w-delikatnym-curry'),
(464,	'Sałatka z paluszkami krabowymi',	'Orientalna',	15,	'łatwy',	'Ryby',	'Mięso Kraba',	'https://www.przepisy.pl/przepis/salatka-z-paluszkami-krabowymi-i-kapusta-pekinska'),
(465,	'Gotowane na parze pikantne marchewki z pomarańczą i orzechami pekan',	'Orientalna',	25,	'łatwy',	'Wege',	'Marchew',	'https://www.przepisy.pl/przepis/gotowane-na-parze-pikantne-marchewki-z-pomarancza-i-orzechami-pekan'),
(466,	'Curry z soczewicy czerwonej',	'Orientalna',	45,	'łatwy',	'Wege',	'Soczewica',	'https://www.przepisy.pl/przepis/curry-z-soczewicy-czerwonej'),
(467,	'Grillowany stek z wołowiny z chrupiąca ciabattą',	'Północnej Afryki',	45,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/grillowany-stek-z-wolowiny-z-chrupiaca-ciabatta'),
(468,	'Tagine z wołowiny z rodzynkami',	'Północnej Afryki',	95,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/tagine-z-wolowiny-z-rodzynkami'),
(469,	'Bobotie czyli afrykańska zapiekanka',	'Północnej Afryki',	60,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/bobotie-czyli-afrykanska-zapiekanka'),
(470,	'Kurczak z ziołami w chrupiących vol-au-ventach',	'Północnej Afryki',	60,	'średni',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-z-ziolami-w-chrupiacych-vol-au-ventach'),
(471,	'Kurczak à la King',	'Północnej Afryki',	30,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-a-la-king-1'),
(472,	'Ryba z rusztu w liściach chrzanu z harissą i limonką',	'Północnej Afryki',	120,	'łatwy',	'Ryby',	'Dorsz',	'https://www.przepisy.pl/przepis/ryba-z-rusztu-w-lisciach-chrzanu-z-harissa-i-limonka'),
(473,	'Jagnięcina w miętowym sosie',	'Polska',	45,	'łatwy',	'Mięso',	'Jagnięcina',	'https://www.przepisy.pl/przepis/jagniecina-w-mietowym-sosi'),
(474,	'Duszona cielęcina',	'Polska',	60,	'łatwy',	'Mięso',	'Cielęcina',	'https://www.przepisy.pl/przepis/duszona-cielecina'),
(475,	'Pstrąg zapiekany',	'Polska',	45,	'łatwy',	'Ryby',	'Pstrąg, Ser',	'https://www.przepisy.pl/przepis/pstrag-zapiekany'),
(476,	'Bitki wołowe z cebulą i octem balsamicznym',	'Polska',	60,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/bitki-wolowe-z-cebula-i-octem-balsamicznym'),
(477,	'Śledzie po kaszubsku z octem',	'Polska',	30,	'średni',	'Ryby',	'Śledź',	'https://www.przepisy.pl/przepis/sledzie-po-kaszubsku-z-octem'),
(478,	'Gulasz wieprzowy po myśliwsku',	'Polska',	45,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/gulasz-wieprzowy-po-mysliwski-z-kielbasa-i-ogorkiem'),
(479,	'Żurek śląski',	'Polska',	60,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/zurek-slaski'),
(480,	'Pyzy z grzybami',	'Polska',	50,	'łatwy',	'Wege',	'Grzyby',	'https://www.przepisy.pl/przepis/pyzy-z-grzybami'),
(481,	'Pieczony kalafior',	'Polska',	25,	'łatwy',	'Wege',	'Kalafior',	'https://www.przepisy.pl/przepis/pieczony-kalafior'),
(482,	'Rolada marchewkowa',	'Polska',	40,	'łatwy',	'Wege',	'Marchew',	'https://www.przepisy.pl/przepis/rolada-marchewkowa'),
(483,	'Pstrąg pikantny',	'Rosyjska',	30,	'średni',	'Ryby',	'Pstrąg',	'https://www.przepisy.pl/przepis/pstrag-pikantny'),
(484,	'Kotlety z łososia',	'Rosyjska',	30,	'łatwy',	'Ryby',	'Łosoś',	'https://www.przepisy.pl/przepis/kotlety-z-lososia'),
(485,	'Haładziec',	'Rosyjska',	90,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/haladziec'),
(486,	'Bliny z wędzoną makrelą',	'Rosyjska',	45,	'łatwy',	'Ryby',	'Makrela',	'https://www.przepisy.pl/przepis/bliny-z-wedzona-makrela'),
(487,	'Kotlety z marchewki',	'Rosyjska',	45,	'łatwy',	'Wege',	'Marchew',	'https://www.przepisy.pl/przepis/kotlety-z-marchewki'),
(488,	'Krokiety z jajek na twardo',	'Rosyjska',	45,	'łatwy',	'Wege',	'Jajko',	'https://www.przepisy.pl/przepis/krokiety-z-jajek-na-twardo'),
(489,	'Placki z kalarepy',	'Rosyjska',	30,	'łatwy',	'Wege',	'Kalarepa',	'https://www.przepisy.pl/przepis/placki-z-kalarepy'),
(490,	'Pikantne kalmary w sosie słodko kwaśnym',	'Śródziemnomorska',	30,	'łatwy',	'Ryby',	'Kalmary',	'https://www.przepisy.pl/przepis/pikantne-kalmary-w-sosie-slodko-kwasnym'),
(491,	'Pstrąg z grilla',	'Śródziemnomorska',	35,	'łatwy',	'Ryby',	'Pstrąg',	'https://www.przepisy.pl/przepis/pstrag-z-grilla'),
(492,	'Kurczak z serową „panierką”',	'Śródziemnomorska',	45,	'średni',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-z-serowa-panierka'),
(493,	'Ceviche z łososia',	'Śródziemnomorska',	15,	'łatwy',	'Ryby',	'Łosoś',	'https://www.przepisy.pl/przepis/ceviche-z-lososia'),
(494,	'Cobanac gulasz chorwacki',	'Śródziemnomorska',	60,	'średni',	'Mięso',	'Jagnięcina',	'https://www.przepisy.pl/przepis/cobanac-gulasz-chorwacki'),
(495,	'Kurczak w cieście',	'Śródziemnomorska',	90,	'średni',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/kurczak-w-ciescie-3'),
(496,	'Krewetki w ostrym sosie',	'Śródziemnomorska',	30,	'łatwy',	'Ryby',	'Krewetki',	'https://www.przepisy.pl/przepis/krewetki-w-ostrym-sosie'),
(497,	'Krewetkowe szaszłyki',	'Śródziemnomorska',	90,	'łatwy',	'Ryby',	'Krewetki',	'https://www.przepisy.pl/przepis/krewetkowe-szaszlyki'),
(498,	'Diabelski przysmak',	'Śródziemnomorska',	30,	'łatwy',	'Wege',	'Makaron',	'https://www.przepisy.pl/przepis/diabelski-przysmak'),
(499,	'Smażone oliwki',	'Śródziemnomorska',	30,	'łatwy',	'Wege',	'Oliwki',	'https://www.przepisy.pl/przepis/smazone-oliwki-1'),
(500,	'Tabbouleh',	'Śródziemnomorska',	35,	'łatwy',	'Wege',	'Kasza',	'http://pomajamu.pl/tabbouleh/'),
(501,	'Tajska wołowina z curry',	'Tajska',	30,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/tajska-wolowina-z-curry'),
(502,	'Tajskie pierożki z musem z kolendry',	'Tajska',	45,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/tajskie-pierozki-z-musem-z-kolendry'),
(503,	'Sataje – tajskie szaszłyki z sosem orzechowym',	'Tajska',	30,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/sataje-czyli-tajskie-szaszlyki-z-sosem-orzechowym'),
(504,	'Sataye z piersi kaczki',	'Tajska',	30,	'łatwy',	'Mięso',	'Kaczka',	'https://www.przepisy.pl/przepis/sataye-z-piersi-kaczki'),
(505,	'Tajska zupa krewetkowa',	'Tajska',	45,	'łatwy',	'Ryby',	'Krewetki',	'https://www.przepisy.pl/przepis/tajska-zupa-krewetkowa'),
(506,	'Wołowina po tajsku',	'Tajska',	30,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/wolowina-po-tajsku'),
(507,	'Omlet tajski',	'Tajska',	45,	'łatwy',	'Mięso',	'Kurczak',	'https://www.przepisy.pl/przepis/omlet-tajski'),
(508,	'Warzywny gulasz z czerwonym curry i napojem kokosowym ',	'Tajska',	35,	'łatwy',	'Wege',	'Ciecierzyca',	'https://www.przepisy.pl/przepis/warzywny-gulasz-z-czerwonym-curry-i-napojem-kokosowym'),
(509,	'Warzywny bulion po Tajsku',	'Tajska',	25,	'łatwy',	'Wege',	'Grzyby',	'https://www.przepisy.pl/przepis/warzywny-bulion-po-tajsku'),
(510,	'Kofty z baraniny',	'Turecka',	45,	'łatwy',	'Mięso',	'Baranina',	'https://www.przepisy.pl/przepis/kafty-z-baraniny'),
(511,	'İmam bayıldı',	'Turecka',	140,	'średni',	'Mięso',	'Wołowina',	'http://www.tureckieprzepisy.pl/dania-glowne/imam-bayildi-baklazan-z-miesem/'),
(512,	'Patlican Kavurma',	'Turecka',	80,	'łatwy',	'Wege',	'Bakłażan',	'http://www.tureckieprzepisy.pl/przekaski/patlican-kavurma-baklazan-z-patelni/'),
(513,	'Gulasz węgierski',	'Węgierska',	60,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/gulasz-wegierski'),
(514,	'Duszone golonki jagnięce z warzywami',	'Węgierska',	60,	'łatwy',	'Mięso',	'Jagnięcina',	'https://www.przepisy.pl/przepis/duszone-golonki-jagniece-z-warzywami'),
(515,	'Karkówka w marynacie pikantnej',	'Węgierska',	90,	'łatwy',	'Mięso',	'Wieprzowina',	'https://www.przepisy.pl/przepis/karkowka-w-marynacie-pikantnej-wegierskiej-video'),
(516,	'Leczo wegetariańskie ',	'Węgierska',	60,	'średni',	'Wege',	'Soja',	'https://www.przepisy.pl/przepis/leczo-wegetarianskie'),
(517,	'Paszteciki z orzechami pecan',	'Węgierska',	60,	'łatwy',	'Wege',	'Bataty',	'https://www.przepisy.pl/przepis/paszteciki-z-orzechami-pecan'),
(518,	'Kremowa zupa paprykowa',	'Węgierska',	30,	'łatwy',	'Wege',	'Papryka',	'https://www.przepisy.pl/przepis/kremowa-zupa-paprykowa-1'),
(519,	'Włoski gulasz Peposo',	'Włoska',	90,	'łatwy',	'Mięso',	'Wołowina',	'https://www.przepisy.pl/przepis/wloski-gulasz-peposo'),
(520,	'Zapiekane roladki z łososia',	'Włoska',	45,	'łatwy',	'Ryby',	'Łosoś',	'https://www.przepisy.pl/przepis/zapiekane-roladki-z-lososia'),
(521,	'Szaszłyk z ananasem',	'Amerykańska',	60,	'łatwy',	'Mięso',	'Ananas, Kurczak',	'https://www.przepisy.pl/przepis/szaszlyk-z-ananasem'),
(522,	'Sałatka teksańska',	'Amerykańska',	30,	'łatwy',	'Mięso',	'Sałata lodowa, Wołowina',	'https://www.przepisy.pl/przepis/salatka-teksanska'),
(523,	'Piersi z kurczaka w kokosie',	'Amerykańska',	45,	'łatwy',	'Mięso',	'Kurczak, Kokos',	'https://www.przepisy.pl/przepis/piersi-z-kurczaka-w-kokosie'),
(524,	'Sałatka Waldorf',	'Amerykańska',	20,	'łatwy',	'Wege',	'Jabłka, Orzechy',	'https://www.przepisy.pl/przepis/burger-z-tunczykiem'),
(525,	'Amerykańskie naleśniki (pancakes)',	'Amerykańska',	30,	'łatwy',	'Wege',	'Naleśniki, Syrop klonowy',	'https://www.przepisy.pl/przepis/amerykanskie-nalesniki-pancakes'),
(526,	'Amerykańska zapiekanka makaronowa',	'Amerykańska',	30,	'łatwy',	'Wege',	'Makaron, Ser',	'https://www.przepisy.pl/przepis/amerykanska-zapiekanka-makaronowa-video'),
(527,	'Pilav',	'Bałkańska',	40,	'łatwy',	'Mięso',	'Wieprzowina, Ryż',	'https://www.przepisy.pl/przepis/pilav'),
(528,	'Makaron po bałkańsku',	'Bałkańska',	30,	'łatwy',	'Mięso',	'Wołowina, Makaron',	'https://www.przepisy.pl/przepis/makaron-po-balkansku'),
(529,	'Grillowane burgery z łososia i krewetek',	'Bałkańska',	15,	'łatwy',	'Ryby',	'Łosoś, Krewetki',	'https://www.przepisy.pl/przepis/grillowane-burgery-z-lososia-i-krewetek'),
(530,	'Naleśnikowy piętrowiec',	'Bałkańska',	60,	'średni',	'Mięso',	'Naleśniki, Wołowina',	'https://www.przepisy.pl/przepis/nalesnikowy-pietrowiec'),
(531,	'Papryka faszerowana z soczewicą',	'Bałkańska',	60,	'łatwy',	'Wege',	'Papryka, Soczewica',	'https://www.przepisy.pl/przepis/papryka-faszerowana-z-soczewica'),
(532,	'Leczo z ziemniakami i kukurydzą',	'Bałkańska',	45,	'średni',	'Wege',	'Ziemniaki, Kukurydza',	'https://www.przepisy.pl/przepis/leczo-z-ziemniakami'),
(533,	'Piersi kurczaka w panierce z orzeszków pinii i migdałów',	'Bliskiego Wschodu',	40,	'łatwy',	'Mięso',	'Kurczak, Orzechy',	'https://www.przepisy.pl/przepis/piersi-kurczaka-w-panierce-z-orzeszkow-pinii-i-migdalow'),
(534,	'Shish kebab',	'Bliskiego Wschodu',	35,	'łatwy',	'Mięso',	'Wołowina, Jagnięcina',	'https://www.przepisy.pl/przepis/shish-kebab'),
(535,	'Imbirowy kurczak z fasolą',	'Chińska',	30,	'łatwy',	'Mięso',	'Kurczak, Fasola',	'https://www.przepisy.pl/przepis/imbirowy-kurczak-z-fasola'),
(536,	'Smażona wołowina z makaronem jajecznym',	'Chińska',	45,	'łatwy',	'Mięso',	'Wołowina, Makaron',	'https://www.przepisy.pl/przepis/smazona-wolowina-z-makaronem-jajecznym'),
(537,	'Ryż smażony z krewetkami',	'Chińska',	30,	'łatwy',	'Ryby',	'Krewetki, Ryż',	'https://www.przepisy.pl/przepis/ryz-smazony-z-krewetkami'),
(538,	'Makaron ryżowy z warzywami i serem tofu po syczuańsku',	'Chińska',	40,	'łatwy',	'Wege',	'Makaron, Tofu',	'https://www.przepisy.pl/przepis/makaron-ryzowy-z-warzywami-i-serem-tofu-po-syczuansku'),
(539,	'Smażony makaron chiński z kapustą',	'Chińska',	25,	'łatwy',	'Wege',	'Makaron, Kapusta',	'https://www.przepisy.pl/przepis/smazony-makaron-chinski-z-kapusta'),
(540,	'Tofu z cukinią',	'Chińska',	45,	'łatwy',	'Wege',	'Tofu, Cukinia',	'https://www.przepisy.pl/przepis/tofu-z-cukinia'),
(541,	'Tarta ze szpinakiem i serem',	'Francuska',	60,	'łatwy',	'Wege',	'Szpinak, Ser',	'https://www.przepisy.pl/przepis/tarta-ze-szpinakiem-i-serem'),
(542,	'Prowansalska tarta z pomidorami',	'Francuska',	60,	'średni',	'Wege',	'Pomidor, Ser',	'https://www.przepisy.pl/przepis/prowansalska-tarta-z-pomidorami'),
(543,	'Krewetki na trawie cytrynowej z grillowanym czosnkiem',	'Fusion',	35,	'łatwy',	'Ryby',	'Łosoś, Krewetki',	'https://www.przepisy.pl/przepis/krewetki-na-trawie-cytrynowej-z-grillowanym-czosnkiem'),
(544,	'Karaibski kurczak z grilla z ananasową salsą',	'Fusion',	50,	'łatwy',	'Mięso',	'Kurczak, Ananas',	'https://www.przepisy.pl/przepis/karaibski-kurczak-z-grilla-z-ananasowa-salsa'),
(545,	'Dolma',	'Grecka',	60,	'średni',	'Mięso',	'Wołowina, Wieprzowina',	'https://www.przepisy.pl/przepis/dolma'),
(546,	'Giouvetsi - grecki gulasz',	'Grecka',	45,	'łatwy',	'Mięso',	'Cielęcina, Wieprzowina',	'https://www.przepisy.pl/przepis/giouvetsi-grecki-gulasz'),
(547,	'Kubdari',	'Gruzińska',	110,	'średni',	'Mięso',	'Wołowina, Wieprzowina',	'https://www.przepisy.pl/przepis/kubdari'),
(548,	'Tradycyjna zupa grochowa',	'Gruzińska',	90,	'średni',	'Mięso',	'Groch, Wieprzowina',	'https://www.przepisy.pl/przepis/tradycyjna-zupa-grochowa'),
(549,	'Saciwi - kurczak w sosie orzechowym',	'Gruzińska',	120,	'średni',	'Mięso',	'Kurczak, Orzechy',	'https://www.polakogruzin.pl/saciwi-gruzinski-przepis-na-kurczaka-w-sosie-orzechowym/'),
(550,	'Czachochbili - kurczak w sosie pomidotrowym',	'Gruzińska',	45,	'łatwy',	'Mięso',	'Kurczak, Pomidor',	'https://www.polakogruzin.pl/czachochbili-gruzinski-przepis-na-kurczaka-w-sosie-pomidorowym/'),
(551,	'Adżapsandali',	'Gruzińska',	60,	'średni',	'Wege',	'Ziemniaki, Bakłażan',	'https://www.przepisy.pl/przepis/adzapsandali'),
(552,	'Risotto z dynią',	'Hiszpańska',	30,	'łatwy',	'Wege',	'Dynia, Ryż',	'https://www.przepisy.pl/przepis/risotto-z-dynia'),
(553,	'Curry z kurczakiem i ananasem',	'Indyjska',	45,	'średni',	'Mięso',	'Kurczak, Ananas',	'https://www.przepisy.pl/przepis/curry-z-kurczakiem-i-ananasem'),
(554,	'Kurczak w mulligatawny',	'Indyjska',	90,	'łatwy',	'Mięso',	'Kurczak, Ryż',	'https://www.przepisy.pl/przepis/kurczak-w-mulligatawny'),
(555,	'Kurczak tikka masala',	'Indyjska',	90,	'łatwy',	'Mięso',	'Kurczak, Pomidor',	'https://www.przepisy.pl/przepis/kurczak-tikka-masala'),
(556,	'Pierożki singharas',	'Indyjska',	60,	'średni',	'Mięso',	'Kurczak, Wołowina',	'https://www.przepisy.pl/przepis/pierozki-singharas'),
(557,	'Indyjski gulasz z soczewicą i boczniakami',	'Indyjska',	60,	'średni',	'Wege',	'Pomidor, Soczewica',	'https://www.przepisy.pl/przepis/indyjski-gulasz-z-soczewica-i-boczniakami'),
(558,	'Faszerowane liście pachnotki',	'Koreańska',	15,	'łatwy',	'mix',	'Wieprzowina, Krewetki',	'https://www.przepisy.pl/przepis/faszerowane-liscie-pachnotki'),
(559,	'Warzywa smażone w cieście tempura z sezamem',	'Koreańska',	15,	'łatwy',	'Wege',	'Ziemniaki, Cukinia',	'https://www.przepisy.pl/przepis/warzywa-smazone-w-ciescie-tempura-z-sezamem'),
(560,	'Heugimja-juk',	'Koreańska',	45,	'łatwy',	'Wege',	'Ryż, Sezam',	'https://smakowity.pl/przepis/heugimja-juk'),
(561,	'Kong-guksu ',	'Koreańska',	25,	'łatwy',	'Wege',	'Soja, Sezam',	'http://www.sfinjak.wroclaw.pl/eggblog/news.php?id=420'),
(562,	'Gołąbki po meksykańsku',	'Meksykańska',	45,	'średni',	'Mięso',	'Wieprzowina, Wołowina',	'https://www.przepisy.pl/przepis/golabki-po-meksykansku'),
(563,	'Sałatka meksykańska z kurczakiem',	'Meksykańska',	45,	'łatwy',	'Mięso',	'Kurczak, Ryż',	'https://www.przepisy.pl/przepis/salatka-meksykanska-z-kurczakiem-1'),
(564,	'Picadillo - nadzienie do tortilli',	'Meksykańska',	30,	'łatwy',	'Mięso',	'Wołowina, Wieprzowina',	'https://www.przepisy.pl/przepis/picadillo-nadzienie-do-tortilli'),
(565,	'Kurczak po meksykańsku z chrupiąca panierką z nachos',	'Meksykańska',	30,	'łatwy',	'Mięso',	'Kurczak, Nachos',	'https://www.przepisy.pl/przepis/kurczak-po-meksykansku-z-chrupiaca-panierka-z-nachos'),
(566,	'Enchiladas wegetariańskie',	'Meksykańska',	35,	'łatwy',	'Wege',	'Pomidor, Czerwona Fasola',	'https://www.przepisy.pl/przepis/enchiladas-wegetarianskie'),
(567,	'Meksykańskie naleśniki z warzywami',	'Meksykańska',	60,	'łatwy',	'Wege',	'Cukinia, Czerwona Fasola',	'https://www.przepisy.pl/przepis/meksykanskie-nalesniki-z-warzywami'),
(568,	'Frytki z dipem guacamole',	'Meksykańska',	60,	'łatwy',	'Wege',	'Ziemniaki, Awokado',	'https://www.przepisy.pl/przepis/frytki-z-dipem-guacamole'),
(569,	'Zupa brokułowa z serkiem topionym',	'Niemiecka',	60,	'łatwy',	'Mięso',	'Wieprzowina, Brokuły',	'https://www.przepisy.pl/przepis/zupa-brokulowa-z-serkiem-topionym'),
(570,	'Ziemniaki faszerowane śledziem',	'Niemiecka',	60,	'średni',	'Ryby',	'Ziemniaki, Śledź',	'https://www.przepisy.pl/przepis/ziemniaki-faszerowane-sledziem'),
(571,	'Gęsta kartoflanka berlińska',	'Niemiecka',	90,	'łatwy',	'Mięso',	'Ziemniaki, Wieprzowina',	'https://www.przepisy.pl/przepis/gesta-kartoflanka-berlinska-1'),
(572,	'Sałatka ze szpeclami',	'Niemiecka',	60,	'łatwy',	'Mięso',	'Makaron, Wieprzowina',	'https://www.przepisy.pl/przepis/salatka-ze-szpeclami'),
(573,	'Currywurst',	'Niemiecka',	30,	'łatwy',	'Mięso',	'Wieprzowina, Wołowina',	'https://www.przepisy.pl/przepis/currywurst'),
(574,	'Żebra po kasselsku',	'Niemiecka',	90,	'trudny',	'Mięso',	'Wieprzowina, Kapusta',	'https://www.przepisy.pl/przepis/zebra-po-kasselsku'),
(575,	'Łosoś pieczony w boczku z sosem musztardowo-miodowym',	'Niemiecka',	60,	'średni',	'mix',	'Łosoś, Wieprzowina',	'https://www.przepisy.pl/przepis/losos-pieczony-w-boczku-z-sosem-musztardowo-miodowym'),
(576,	'Cesarski placek z sosem waniliowym',	'Niemiecka',	30,	'łatwy',	'Wege',	'Gruszka, Placek',	'https://www.przepisy.pl/przepis/kaiserschmarn-czyli-cesarski-placek-z-sosem-waniliowym-1'),
(577,	'Ziemniak pieczony z serem',	'Niemiecka',	60,	'łatwy',	'Wege',	'Ziemniaki, Ser',	'https://www.przepisy.pl/przepis/ziemniak-pieczony-z-serem'),
(578,	'Sałatka makaronowa z tuńczykiem',	'Orientalna',	20,	'łatwy',	'Ryby',	'Tuńczyk, Makaron',	'https://www.przepisy.pl/przepis/salatka-makaronowa-z-tunczykiem'),
(579,	'Pierożki gyoza',	'Orientalna',	45,	'łatwy',	'Wege',	'Włoszczyzna, Pierogi',	'https://www.przepisy.pl/przepis/pierozki-gyoza'),
(580,	'Indyjskie ziemniaki z ciecierzycą',	'Orientalna',	50,	'łatwy',	'Wege',	'Ziemniaki, Ciecierzyca',	'https://www.przepisy.pl/przepis/indyjskie-ziemniaki-z-ciecierzyca'),
(581,	'Pieczone Falafel’e z miętowym sosem Tahini na ostro',	'Orientalna',	35,	'łatwy',	'Wege',	'Kasza, Sezam',	'https://www.przepisy.pl/przepis/pieczone-falafele-z-mietowym-sosem-tahini-na-ostro'),
(582,	'Stek Surf&Turf',	'Północnej Afryki',	30,	'średni',	'mix',	'Wołowina, Krewetki',	'https://www.przepisy.pl/przepis/stek-surfandturf'),
(583,	'Ziemniaki Bolognese',	'Północnej Afryki',	60,	'łatwy',	'Mięso',	'Ziemniaki, Wołowina',	'https://www.przepisy.pl/przepis/ziemniaki-bolognese-1'),
(584,	'Kefta tagine',	'Północnej Afryki',	35,	'łatwy',	'Mięso',	'Wołowina, Jagnięcina',	'https://www.przepisy.pl/przepis/kefta-tagine'),
(585,	'Chakalaka - gulasz warzywny',	'Północnej Afryki',	30,	'łatwy',	'Wege',	'Marchew, Kapusta',	'https://www.przepisy.pl/przepis/chakalaka-gulasz-warzywny-video'),
(586,	'Pikantna marokańska sałatka z kaszy jaglanej i soczewicy',	'Północnej Afryki',	50,	'łatwy',	'Wege',	'Kasza, Soczewica',	'https://www.przepisy.pl/przepis/pikantna-marokanska-salatka-z-kaszy-jaglanej-i-soczewicy'),
(587,	'Zupa z błękitnym serem i rzeżuchą',	'Północnej Afryki',	30,	'łatwy',	'Wege',	'Ser, Rzeżucha',	'https://www.przepisy.pl/przepis/zupa-z-blekitnym-serem-i-rzezucha'),
(588,	'Ragout warzywne',	'Północnej Afryki',	30,	'łatwy',	'Wege',	'Dynia, Cukinia',	'https://www.przepisy.pl/przepis/ragout-warzywne'),
(589,	'Sałatka z bulgurem i hummusem',	'Północnej Afryki',	30,	'łatwy',	'Wege',	'Kasza, Ciecierzyca',	'https://www.przepisy.pl/przepis/salatka-z-bulgurem-i-hummusem'),
(590,	'Roladki wieprzowe',	'Polska',	60,	'łatwy',	'Mięso',	'Wieprzowina, Szpinak',	'https://www.przepisy.pl/przepis/roladki-wieprzowe'),
(591,	'Zupa z kalarepy i rzodkiewek',	'Polska',	60,	'łatwy',	'Wege',	'Kalarepa, Rzodkiew',	'https://www.przepisy.pl/przepis/zupa-z-kalarepy-i-rzodkiewek'),
(592,	'Stroganoff z kurczaka z porami',	'Rosyjska',	30,	'łatwy',	'Mięso',	'Kurczak, Por',	'https://www.przepisy.pl/przepis/stroganoff-z-kurczaka-z-porami'),
(593,	'Kulebiak rybny z łososiem',	'Rosyjska',	90,	'łatwy',	'Ryby',	'Łosoś, Włoszczyzna',	'https://www.przepisy.pl/przepis/kulebiak-rybny-z-lososiem'),
(594,	'Kapusta faszerowana mięsem',	'Rosyjska',	90,	'średni',	'Mięso',	'Wołowina, Kapusta',	'https://www.przepisy.pl/przepis/kapusta-faszerowana-miesem'),
(595,	'Kura zapiekana w majonezie',	'Rosyjska',	60,	'łatwy',	'Mięso',	'Kurczak, Ziemniaki',	'https://www.przepisy.pl/przepis/kura-zapiekana-w-majonezie'),
(596,	'Sandacz po rosyjsku',	'Rosyjska',	60,	'łatwy',	'Ryby',	'Sandacz, Dorsz',	'https://www.przepisy.pl/przepis/sandacz-po-rosyjsku'),
(597,	'Szczupak w sosie szafranowym',	'Rosyjska',	90,	'łatwy',	'Ryby',	'Szczupak, Pstrąg',	'https://www.przepisy.pl/przepis/szczupak-w-sosie-szafranowym'),
(598,	'Kulebiak z kapustą kiszoną',	'Rosyjska',	90,	'średni',	'Wege',	'Kapusta, Grzyby',	'https://www.przepisy.pl/przepis/kulebiak-z-kapusta-kiszona'),
(599,	'Kotleciki rybne z kolendrą',	'Śródziemnomorska',	45,	'łatwy',	'Ryby',	'Dorsz, Krewetki',	'https://www.przepisy.pl/przepis/kotleciki-rybne-z-kolendra'),
(600,	'Sałatka z karczochem i bobem',	'Śródziemnomorska',	60,	'średni',	'Wege',	'Bób, Karczochy',	'https://www.przepisy.pl/przepis/salatka-z-karczochem-i-bobem'),
(601,	'Makaron z sosem szpinakowym',	'Śródziemnomorska',	45,	'średni',	'Wege',	'Makaron, Szpinak',	'https://www.przepisy.pl/przepis/makaron-z-sosem-szpinakowym'),
(602,	'Zupa Tom Yum z krewetkami',	'Tajska',	30,	'łatwy',	'Ryby',	'Krewetki, Grzyby',	'https://www.przepisy.pl/przepis/zupa-tom-yum-z-krewetkami'),
(603,	'Ostre skrzydełka w tajskim stylu z zieloną fasolką szparagową',	'Tajska',	40,	'łatwy',	'Mięso',	'Kurczak, Fasola Szparagowa',	'https://www.przepisy.pl/przepis/ostre-skrzydelka-w-tajskim-stylu-z-zielona-fasolka-szparagowa'),
(604,	'Pad thai z tofu',	'Tajska',	40,	'średni',	'Wege',	'Tofu, Makaron',	'https://www.przepisy.pl/przepis/pad-thai-z-tofu'),
(605,	'Ryż na napoju kokosowym z mango i bananem',	'Tajska',	30,	'łatwy',	'Wege',	'Napój kokosowy, Mango',	'https://www.przepisy.pl/przepis/ryz-na-napoju-kokosowym-z-mango-i-bananem'),
(606,	'Kotleciki z batatów z sosem pomidorowo-sojowym',	'Tajska',	45,	'średni',	'Wege',	'Bataty, Pomidor',	'https://www.przepisy.pl/przepis/kotleciki-z-batatow-z-sosem-pomidorowo-sojowym'),
(607,	'Kabak Dolmasi, czyli faszerowana cukinia',	'Turecka',	70,	'łatwy',	'Mięso',	'Cukinia, Wołowina',	'https://www.przepisy.pl/przepis/kabak-dolmasi-czyli-faszerowana-cukinia'),
(608,	'Kurczak pieczony w mleku z orzechami',	'Turecka',	90,	'łatwy',	'Mięso',	'Kurczak, Orzechy',	'https://www.przepisy.pl/przepis/kurczak-pieczony-w-mleku-z-orzechami-video'),
(609,	'Turecki pilaw z jagnięciny',	'Turecka',	30,	'łatwy',	'Mięso',	'Jagnięcina, Ryż',	'https://www.przepisy.pl/przepis/turecki-pilaw-z-jagnieciny'),
(610,	'Kumpir turecki – zapiekany ziemniak',	'Turecka',	45,	'łatwy',	'Mięso',	'Ziemniaki, Wieprzowina',	'https://www.przepisy.pl/przepis/kumpir-turecki-zapiekany-ziemniak'),
(611,	'Pita z jagnięciną',	'Turecka',	60,	'łatwy',	'Mięso',	'Jagnięcina, Pieczywo',	'https://www.przepisy.pl/przepis/pita-z-jagniecina-1'),
(612,	'Simit',	'Turecka',	60,	'łatwy',	'Wege',	'Pieczywo, Sezam',	'http://www.tureckieprzepisy.pl/potrawy-maczne/simit-czyli-tureckie-precle-sezamem/'),
(613,	'Borek szpinakowy z chlebem yufka',	'Turecka',	60,	'łatwy',	'Wege',	'Pieczywo, Szpinak',	'https://www.przepisy.pl/przepis/boerek-szpinakowy-z-chlebem-yufka-ispanakli-yufka-boeregi'),
(614,	'Şekerpare',	'Turecka',	40,	'łatwy',	'Wege',	'Pieczywo, Cytryna',	'http://www.tureckieprzepisy.pl/desery/sekerpare-ciasteczka-z-syropem-cytrynowym/'),
(615,	'Bogracz',	'Węgierska',	60,	'łatwy',	'Mięso',	'Wołowina, Ziemniaki',	'https://www.przepisy.pl/przepis/bogracz'),
(616,	'Zupa paprykowa z pulpetami',	'Węgierska',	60,	'łatwy',	'Mięso',	'Papryka, Wieprzowina',	'https://www.przepisy.pl/przepis/zupa-paprykowa-z-pulpetami'),
(617,	'Leczo z makaronem',	'Węgierska',	30,	'łatwy',	'Mięso',	'Kurczak, Makaron',	'https://www.przepisy.pl/przepis/leczo-z-makaronem'),
(618,	'Kociołek domowy',	'Węgierska',	45,	'łatwy',	'Mięso',	'Wieprzowina, Ziemniaki',	'https://www.przepisy.pl/przepis/kociolek-domowy'),
(619,	'Ziemniaczany langosz z serem',	'Węgierska',	105,	'łatwy',	'Wege',	'Ziemniaki, Ser',	'https://www.przepisy.pl/przepis/ziemniaczany-langosz-z-serem'),
(620,	'Zielona zupa minestrone z wędzoną cielęciną',	'Włoska',	60,	'trudny',	'Mięso',	'Cielęcina, Szpinak',	'https://www.przepisy.pl/przepis/zielona-zupa-minestrone-z-wedzona-cielecina'),
(621,	'Roladki Saltimbocca alla Romana',	'Włoska',	30,	'łatwy',	'Mięso',	'Cielęcina, Wieprzowina',	'https://www.przepisy.pl/przepis/roladki-saltimbocca-alla-romana'),
(622,	'Włoskie gnocchi z cukinią',	'Włoska',	105,	'łatwy',	'Mięso',	'Wołowina, Cukinia',	'https://www.przepisy.pl/przepis/wloskie-gnocchi-z-cukinia'),
(623,	'Pulpety z indyka w sosie pomidorowym',	'Włoska',	45,	'łatwy',	'Mięso',	'Indyk, Pomidory',	'https://www.przepisy.pl/przepis/pulpety-z-indyka-w-sosie-pomidorowym2'),
(624,	'Pappardelle z małżami i szynką parmeńską',	'Włoska',	15,	'łatwy',	'Mięso',	'Wieprzowina, Makaron',	'https://www.przepisy.pl/przepis/pappardelle-z-malzami-i-szynka-parmenska'),
(625,	'Bruschetta z marynowanymi pomidorami',	'Włoska',	15,	'łatwy',	'Wege',	'Pomidory, Pieczywo',	'https://www.przepisy.pl/przepis/bruschetta-z-marynowanymi-pomidorami'),
(626,	'Focaccia z pomidorami',	'Włoska',	90,	'łatwy',	'Wege',	'Pomidory, Pieczywo',	'https://www.przepisy.pl/przepis/focaccia-z-pomidorami'),
(627,	'Bułki drożdżowe faszerowane soczewicą',	'Włoska',	60,	'łatwy',	'Wege',	'Pieczywo, Soczewica',	'https://www.przepisy.pl/przepis/bulki-drozdzowe-faszerowane-soczewica'),
(628,	'Gęsta zupa z zielonej soczewicy',	'Włoska',	60,	'łatwy',	'Wege',	'Soczewica, Włoszczyzna',	'https://www.przepisy.pl/przepis/gesta-zupa-z-zielonej-soczewicy'),
(629,	'Cevapcici w plackach pity',	'Bałkańska',	50,	'łatwy',	'Mięso',	'Wieprzowina, Wołowina, Jagnięcina',	'https://www.przepisy.pl/przepis/cevapcici-w-plackach-pity'),
(630,	'Szpinakowa sałatka z pieczonymi marchewką i pietruszką',	'Bałkańska',	45,	'łatwy',	'Wege',	'Szpinak, Marchew, Pietruszka',	'https://www.przepisy.pl/przepis/szpinakowa-salatka-z-pieczonymi-marchewka-i-pietruszka'),
(631,	'Kefta tagine',	'Bliskiego Wschodu',	45,	'łatwy',	'Mięso',	'Wołowina, Jagnięcina, Pomidor',	'https://www.przepisy.pl/przepis/kefta-tagine'),
(632,	'Chińskie pierożki',	'Chińska',	30,	'łatwy',	'mix',	'Wieprzowina, Krewetki, Pierogi',	'https://www.przepisy.pl/przepis/chinskie-pierozki'),
(633,	'Ratatouille z kiełbasą chorizo',	'Francuska',	45,	'łatwy',	'Mięso',	'Wieprzowina, Cukinia, Bakłażan',	'https://www.przepisy.pl/przepis/ratatouille-z-kielbasa-chorizo-1'),
(634,	'Chinkali - Gruzińskie pierożki',	'Gruzińska',	45,	'trudny',	'Mięso',	'Wołowina, Wieprzowina, Jagnięcina',	'https://www.przepisy.pl/przepis/chinkali-gruzinskie-pierozki-2'),
(635,	'Paella z owocami morza',	'Hiszpańska',	45,	'łatwy',	'mix',	'Krewetki, Kurczak, Małże',	'https://www.przepisy.pl/przepis/paella-z-owocami-morza'),
(636,	'Zupa z soczewicy z jamon serrano',	'Hiszpańska',	60,	'średni',	'Mięso',	'Soczewica, Wołowina, Wieprzowina',	'https://www.przepisy.pl/przepis/zupa-z-soczewicy-z-jamon-serrano'),
(637,	'Okoń morski z omułkami i hiszpańską kiełbasą',	'Hiszpańska',	45,	'trudny',	'mix',	'Okoń, Wieprzowina, Małże',	'https://www.przepisy.pl/przepis/okon-morski-z-omulkami-i-hiszpanska-kielbasa'),
(638,	'Omlet z cukinią i pomidorami',	'Hiszpańska',	15,	'łatwy',	'Wege',	'Jajko, Cukinia, Pomidor',	'https://www.przepisy.pl/przepis/omlet-z-cukinia-i-pomidorami'),
(639,	'Indyjskie placuszki dosa z warzywami i humusem',	'Indyjska',	85,	'łatwy',	'Wege',	'Soczewica, Cukinia, Bakłażan',	'https://www.przepisy.pl/przepis/indyjskie-placuszki-dosa-z-warzywami-i-humusem'),
(640,	'Koreańskie pierożki mandu z mięsnym farszem',	'Koreańska',	50,	'łatwy',	'Mięso',	'Tofu, Wieprzowina, Wołowina',	'https://www.przepisy.pl/przepis/koreanskie-pierozki-mandu-z-miesnym-farszem'),
(641,	'Chili sin carne - wegańska wersja Texas chili',	'Meksykańska',	40,	'łatwy',	'Wege',	'Tofu, Soczewica, Pomidor',	'https://www.przepisy.pl/przepis/chili-sin-carne-weganska-wersja-texas-chili'),
(642,	'Tajska zupa z owocami morza',	'Orientalna',	30,	'łatwy',	'Ryby',	'Łosoś, Krewetki, Dorsz',	'https://www.przepisy.pl/przepis/tajska-zupa-z-owocami-morza'),
(643,	'Zupa harira',	'Północnej Afryki',	90,	'łatwy',	'Mięso',	'Wołowina, Ciecierzyca, Soczewica',	'https://www.przepisy.pl/przepis/zupa-harira-2'),
(644,	'Gołąbki z młodej kapusty w sosie pomidorowym',	'Polska',	60,	'łatwy',	'Mięso',	'Wieprzowina, Wołowina, Kapusta',	'https://www.przepisy.pl/przepis/golabki-z-mlodej-kapusty-w-sosie-pomidorowym'),
(645,	'Pierogi z mięsem i grzybami',	'Polska',	60,	'średni',	'Mięso',	'Wieprzowina, Wołowina, Grzyby',	'https://www.przepisy.pl/przepis/pierogi-z-miesem-i-grzybami'),
(646,	'Kotlety z kaszy gryczanej z buraczkami',	'Polska',	70,	'łatwy',	'Wege',	'Kasza, Ser, Buraki',	'https://www.przepisy.pl/przepis/kotlety-z-kaszy-gryczanej-z-buraczkami'),
(647,	'Rosyjska sałatka jarzynowa',	'Rosyjska',	45,	'łatwy',	'Wege',	'Marchew, Ziemniaki, Ogórki',	'https://www.przepisy.pl/przepis/rosyjska-salatka-jarzynowa'),
(648,	'Penne z owocami morza',	'Śródziemnomorska',	20,	'łatwy',	'Ryby',	'Makaron, Krewetki, Mięso Kraba',	'https://www.przepisy.pl/przepis/penne-z-owocami-morza'),
(649,	'Pad Thai',	'Tajska',	30,	'łatwy',	'Mięso',	'Wołowina, Wieprzowina, Kurczak',	'https://www.przepisy.pl/przepis/pad-thai'),
(650,	'Chevapchichi z ajvarem',	'Turecka',	60,	'średni',	'Mięso',	'Wołowina, Wieprzowina, Jagnięcina',	'https://www.przepisy.pl/przepis/chevapchichi-z-ajvarem'),
(651,	'Sarmale',	'Turecka',	60,	'łatwy',	'Mięso',	'Wołowina, Wieprzowina, Kapusta',	'https://www.przepisy.pl/przepis/sarmale'),
(652,	'Shoarma z kurczakiem i serem',	'Turecka',	45,	'łatwy',	'Mięso',	'Kurczak, Ser, Pieczywo',	'https://www.przepisy.pl/przepis/shoarma-z-kurczakiem-i-serem'),
(653,	'Ispanakli Peynirli Gül Böreği',	'Turecka',	40,	'łatwy',	'Wege',	'Pieczywo, Ser, Szpinak',	'http://www.tureckieprzepisy.pl/potrawy-maczne/ispanakli-peynirli-gul-boregi-okragle-bulki-ze-szpinakiem-i-serem/'),
(654,	'Węgierska zupa rybna',	'Węgierska',	45,	'średni',	'Ryby',	'Łosoś, Dorsz, Karp',	'https://www.przepisy.pl/przepis/wegierska-zupa-rybna'),
(655,	'Placek po węgiersku z dwoma rodzajami mięs',	'Węgierska',	60,	'łatwy',	'Mięso',	'Wołowina, Wieprzowina, Ziemniaki',	'https://www.przepisy.pl/przepis/placek-po-wegiersku-z-dwoma-rodzajami-mies-1'),
(656,	'Langosz z gulaszem wołowym',	'Węgierska',	75,	'łatwy',	'Mięso',	'Wołowina, Ziemniaki, Placek',	'https://www.przepisy.pl/przepis/langosz-z-gulaszem-wolowym'),
(657,	'Papryki nadziewane',	'Węgierska',	45,	'łatwy',	'Wege',	'Papryka, Oliwki, Ser',	'https://www.przepisy.pl/przepis/papryki-nadziewane'),
(658,	'Lasagne z owocami morza',	'Włoska',	45,	'łatwy',	'Ryby',	'Mięso Kraba, Krewetki, Makaron',	'https://www.przepisy.pl/przepis/lasagne-z-owocami-morza'),
(659,	'Makaron po bolońsku',	'Włoska',	60,	'łatwy',	'Mięso',	'Wołowina, Wieprzowina, Makaron',	'https://www.przepisy.pl/przepis/makaron-po-bolonsku'),
(660,	'Pizza sycylijska',	'Włoska',	45,	'łatwy',	'Ryby',	'Sardelki, Ser, Pieczywo',	'https://www.przepisy.pl/przepis/pizza-sycylijska'),
(661,	'Risotto z warzywami',	'Włoska',	30,	'łatwy',	'Wege',	'Ryż, Szparagi, Groszek',	'https://www.przepisy.pl/przepis/risotto-z-warzywami');



